name: novda
description: "A baby caring app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  novda_sdk:
    path: packages/novda_sdk
  novda_core:
    path: packages/novda_core
  novda_components:
    path: packages/novda_components
  adaptive_platform_ui: ^0.1.101
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/tabs/
    - assets/images/profile/
    - assets/images/others/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Geist-Black.ttf
          weight: 900
