name: novda_sdk
description: SDK for Novda baby care app - provides use cases and models for API interaction
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
